"""empty message

Revision ID: 78706a1f5af9
Revises: 867016fee9ea
Create Date: 2025-01-25 20:11:53.377171

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78706a1f5af9'
down_revision = '867016fee9ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.add_column(sa.Column('homeworld', sa.String(length=50)))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.drop_column('homeworld')

    # ### end Alembic commands ###
